name: Build and deploy to GAE

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - working-directory: ./cm-backend
      run: npm ci
    - working-directory: ./cm-backend
      run: npx tsc
    - working-directory: ./cm-frontend
      run: npm ci
    - working-directory: ./cm-frontend
      run: npx ng build --prod
    - uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        working_directory: ./cm-backend
